# Generated by Django 3.1.7 on 2021-03-15 06:53

import app1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='姓名')),
                ('phone', models.IntegerField(unique=True, verbose_name='电话')),
                ('max_borrowing', models.IntegerField(default=5, verbose_name='可借数量')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('photo', models.ImageField(blank=True, upload_to=app1.models.custom_path, verbose_name='头像')),
                ('status', models.IntegerField(choices=[(0, 'normal'), (-1, 'overdue')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
            },
        ),
    ]
