# Generated by Django 3.1.7 on 2021-03-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='借出时间')),
                ('date_due_to_returned', models.DateField(verbose_name='应还时间')),
                ('date_returned', models.DateField(null=True, verbose_name='还书时间')),
                ('amount_of_fine', models.FloatField(default=0.0, verbose_name='欠款')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book', verbose_name='ISBN')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '借阅',
                'verbose_name_plural': '借阅',
            },
        ),
    ]
