# Generated by Django 3.1.7 on 2021-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('directions', models.TextField(verbose_name='说明')),
                ('config', models.TextField(verbose_name='配置')),
                ('date_issued', models.DateField(verbose_name='上传时间')),
                ('hex', models.BinaryField(verbose_name='程序')),
            ],
        ),
    ]
